theme: jekyll-theme-cayman

title: TJ's Digital Survival Guide
description: "This is my website. I'll probably completely change it again in 15 minutes. For now it's tips and tricks on surviving the digital age."
show_downloads: false
